apiVersion: v1
kind: Pod
metadata:
  name: aiohttp-demo
spec:
  containers:
    - image: localhost:5000/aiohttp-demo:latest
      name: aiohttp-demo
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
