apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      app: kubia
    spec:
      containers:
        - name: kubia
          image: localhost:5000/aiohttp-demo:latest
          ports:
            - containerPort: 8080
