apiVersion: v1
kind: ReplicationController
metadata:
  name: aiohttp-demo
spec:
  replicas: 3
  selector:
    app: aiohttp-demo
  template:
    metadata:
      labels:
        app: aiohttp-demo
    spec:
      containers:
      - name: kubia
        image: localhost:5000/aiohttp-demo:latest
        ports:
        - containerPort: 8080
